# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

# Your own specialized rules go here

require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-i18n
  - rubocop-performance
  - rubocop-rails
  - rubocop-thread_safety
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails

Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/application_controller.rb'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/**/*.rb'
    - 'lib/**/*.rake'

Layout/LineLength:
  Exclude:
    - 'config/**/*.rb'

Rails/BulkChangeTable:
  Exclude:
    - 'db/migrate/*'

I18n/RailsI18n:
  Enabled: true
I18n/GetText:
  Enabled: false
I18n/RailsI18n/DecorateString:
  Exclude:
    - 'db/seeds.rb'
    - 'spec/helpers/user_helper_spec.rb'

# Just noise at the moment
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/RepeatedExample:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/IdenticalEqualityAssertion:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false

Layout/LineLength:
  Enabled: false
