require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-i18n
  - rubocop-performance
  - rubocop-rails
  - rubocop-thread_safety
  # TODO: Re-enable these cops and fix (low priority)
  # - rubocop-rspec
  # - rubocop-rspec_rails

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
  Exclude:
    - 'config/**/*.rb'

Layout/LineLength:
  Enabled: false
  Exclude:
    - 'config/**/*.rb'

I18n/RailsI18n:
  Enabled: true
I18n/GetText:
  Enabled: false
I18n/RailsI18n/DecorateString:
  Exclude:
    - 'db/seeds.rb'
