version: '3.8'

services:
  forum:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    depends_on:
      - db-forum

  db-forum:
    image: postgres:17
    env_file:
      - .env.production
    volumes:
      - forum-pgdata:/var/lib/postgresql/data

volumes:
  forum-pgdata: