version: '3.8'

services:
  forum:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    depends_on:
      - db_forum

  db_forum:
    image: postgres:16
    env_file:
      - .env.production
    volumes:
      - forum_pgdata:/var/lib/postgresql/data

volumes:
  forum_pgdata: