# Exported from Render on 2024-04-22T00:31:53Z
databases:
- name: forum
  databaseName: forum_b1cm
  user: forum
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
version: "1"

# Exported from Render on 2024-04-22T00:31:17Z
services:
- type: web
  name: forum
  runtime: ruby
  repo: https://github.com/HarrisFauntleroy/forum
  plan: free
  envVars:
  - key: SECRET_KEY_BASE
    sync: false
  - key: DISABLE_DATABASE_ENVIRONMENT_CHECK
    sync: false
  - key: DATABASE_URL
    sync: false
  region: oregon
  buildCommand: ./bin/render-build.sh
  startCommand: bundle exec puma -C config/puma.rb
  autoDeploy: false
version: "1"
